### ISSUE TITLE
deprecate imports from mantra-core

### ISSUE THREAD

**Issue by markshust** [mantrajs/mantra-core#8]
I'm wondering if the pulled in imports from `react-simple-di` and `react-komposer` should perhaps be deprecated?

Right now `react-komposer` is on version 1.9.0 and there are some pending pr's for `react-simple-di`. I'm concerned this repo that imports them into mantra-core package will always be slightly outdated unless an automated build is setup. Since this is the case, I'm wondering if these wrapper functions should be deprecated.

**Comment by chmanie** [comment]
I was worried about similar things. In the end, this package mainly is one _small_ file that you can easily fork/copy and include in your project. I actually ended up doing exactly that (see also #5).

**Comment by markshust** [comment]
Thanks. I did wind up forking & updating. I think in a larger project, this wrapper helps so we don't have many lines of imports (same reason we are using DI).

I'll close this out, as I opened a ticket to update mantra-core with the latest versions at https://github.com/mantrajs/mantra-core/issues/6 -- we can still discuss here though if needed.
